### PR TITLE
Fix french translation

### PR DESCRIPTION
**Pull request by oliverpool**
### Pull Request Summary

Fix a typo in the french translation

### CODE REVIEW

**Comment by micalm** [comment]
@karsasmus This should be moved to a separate repo, like other actively maintained translations.

**Comment by karsasmus** [comment]
Hi @oliverpool,

thanks for your PR. Would you mind creating a PR at https://github.com/Leafpub/fr-fr ?
The language files will be in separated repos, so we're able to update the language files individually. 🙂

**Comment by oliverpool** [comment]
Done.

Maybe you could add a "README" or a "READ_BEFORE_PR" in the language folder to list the correct repos for the PR.

**Comment by m1guelpf** [comment]
Don't you have also an Spanish translation? I can't find it

**Comment by karsasmus** [comment]
@m1guelpf it's online now 🙂 https://github.com/Leafpub/es

**Pull request closed without merging**
