### PR TITLE
Add translation guidelines

### PR DESCRIPTION
**Pull request by oliverpool**
To prevent issues like #115.

I listed only one language, for you to see.

If you think it's a good idea, let's add the remaining languages!

(One could also add some comments about how to use them in the templates)

### CODE REVIEW

**Comment by m1guelpf** [comment]
@oliverpool Looks good!

**Comment by karsasmus** [comment]
Thank you for your PR. 
I've updated the [CONTRIBUTING.md](https://github.com/Leafpub/leafpub/blob/master/.github/CONTRIBUTING.md#languages) and added the language repos. 🙂 

So we don't need to add a ReadMe.md in the language folder.

I've also added missing translations to all languages files.

Sorry for the inconvenience with the translation files.

**Comment by oliverpool** [comment]
I would still recommend a file in the language folder (pointing to the updated *contributing guidelines*).

This is how I did it:
- I saw the mistake
- searched the faulty sentence in the whole code
- looked at the `languages` folder on github, and proposed a PR (I do apologize for not reading the contributing guidelines, since it was only a "one character PR")

A `README` in the languages folder could have prevented my mistake !

I also recommend a line in the front-page readme (since people who fix a translation do need to be developers)

**Comment by karsasmus** [comment]
What about the following addition to README.md? :slightly_smiling_face: 

> Something is wrong with a translation? Your language isn't available? Please read through the [language section](https://github.com/leafpub/leafpub/blob/master/.github/CONTRIBUTING.md#languages)

**Pull request closed without merging**
